﻿syntax = "proto3";

option csharp_namespace = "CarDealer.GrpcProtos";

package GrpcProtos;

﻿import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";
import "common.proto";
import "ModuleIIoT.proto";

service Message {

	rpc CreateMessage (CreateMessageRequest) returns (MessageDTO);
	rpc GetMessage(GetRequest) returns (NullableMessageDTO);
	rpc GetAllMessages (google.protobuf.Empty) returns (Messages);
	rpc UpdateMessage (MessageDTO) returns (google.protobuf.Empty);
	rpc DeleteMessage (DeleteMessage) returns (google.protobuf.Empty);

}

message MessageDTO{
	string id=1;
	string text=2;
    google.protobuf.Timestamp creationMessage = 3;
	ModuleIIoT moduleIIoT=4;
}
message Message{
	repeated MessageDTO items = 1;
}

message NullableMessageDTO{
	oneof kind{
		google.protobuf.NullValue null = 1;
		MessageDTO message = 2;
	}
	
}
message CreateMessage{
		string text=1;
		ModuleIIoT moduleIIoT=2;
		google.protobuf.Timestamp creationMessage = 3;

	}