syntax = "proto3";

option csharp_namespace = "ModuleCentralizationIIoT.GrpcProtos.ModulesIIoT";

package GrpcProtos;

import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";
import "common.proto";


service ModuleIIoT{
	rpc CreateModuleIIoT (CreateModuleIIoTRequest) returns (ModuleIIoTDTO);
	rpc GetModuleIIoT (GetRequest) returns (NullableModuleIIoTDTO);
	rpc GetAllModuleIIoT (google.protobuf.Empty) returns (ModulesIIoT);
	rpc UpdateModuleIIoT (ModuleIIoTDTO) returns (google.protobuf.Empty);
	rpc DeleteModuleIIoT (DeleteRequest) returns (google.protobuf.Empty);
}



message ModulesIIoT{
	repeated ModuleIIoTDTO items = 1;
}

message NullableModuleIIoTDTO{
	oneof kind{
		google.protobuf.NullValue null = 1;
		ModuleIIoTDTO moduleIIoT = 2;
	}

}
message CreateModuleIIoTRequest{
	string name=1;
	string addressIp=2;
}
message ModuleIIoTDTO{
	string id=1;
	string name=2;
	string addressIp=3;
	string accessport=4;
	bool isConnected=5;
}