<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<Protobuf Include="*.proto" GrpcServices="Both" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Google.Protobuf" Version="3.27.3" />
	  <PackageReference Include="Grpc.AspNetCore" Version="2.65.0" />
	</ItemGroup>
	
	<ItemGroup>
	  <None Update="common.proto">
	    <GrpcServices>Server</GrpcServices>
	  </None>
	  <None Update="Unity.proto">
	    <GrpcServices>Server</GrpcServices>
	  </None>
	  <None Update="Message.proto">
	    <GrpcServices>Server</GrpcServices>
	  </None>
	</ItemGroup>

</Project>
