syntax = "proto3";

option csharp_namespace = "ModuleCentralizationIIoT.GrpcProtos.Unity";

package GrpcProtos;

import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";
import "common.proto";

service Unity{
	rpc CreateUnity(CreateUnityRequest) returns (UnityDTO);
	rpc GetUnity(GetRequest) returns (NullableUnityDTO);
	rpc GetAllUnity(google.protobuf.Empty) returns (Unities);
	rpc UpdateUnity (UnityDTO) returns (google.protobuf.Empty);
	rpc DeleteUnity (DeleteRequest) returns (google.protobuf.Empty);

}
message UnityDTO{
	string id=1;
	string name=2;
	string code=3;
	string area=4;
}

message Unities{
	repeated UnityDTO items = 1;
}

message NullableUnityDTO{
	oneof kind{
		google.protobuf.NullValue null = 1;
		UnityDTO unity = 2;
	}

}
message CreateUnityRequest{
	string code=1;
	string name=2;
	string area=3;

}