// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModuleCentralizationIIoT.DataAccess.Contexts;

#nullable disable

namespace ModuleCentralizationIIoT.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.31");

            modelBuilder.Entity("ModuleCentralizationIIoT.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModuleIIoTId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleIIoTId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("ModuleCentralizationIIoT.Domain.Entities.ModuleIIoT", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessPort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddresIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModuleIIoT", (string)null);
                });

            modelBuilder.Entity("ModuleCentralizationIIoT.Domain.Entities.Unity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Unity", (string)null);
                });

            modelBuilder.Entity("ModuleIIoTUnity", b =>
                {
                    b.Property<Guid>("ModuleIIoTsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnitiesId")
                        .HasColumnType("TEXT");

                    b.HasKey("ModuleIIoTsId", "UnitiesId");

                    b.HasIndex("UnitiesId");

                    b.ToTable("ModuleIIoTUnity");
                });

            modelBuilder.Entity("ModuleCentralizationIIoT.Domain.Entities.Message", b =>
                {
                    b.HasOne("ModuleCentralizationIIoT.Domain.Entities.ModuleIIoT", "ModuleIIoT")
                        .WithMany("Messages")
                        .HasForeignKey("ModuleIIoTId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleIIoT");
                });

            modelBuilder.Entity("ModuleIIoTUnity", b =>
                {
                    b.HasOne("ModuleCentralizationIIoT.Domain.Entities.ModuleIIoT", null)
                        .WithMany()
                        .HasForeignKey("ModuleIIoTsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModuleCentralizationIIoT.Domain.Entities.Unity", null)
                        .WithMany()
                        .HasForeignKey("UnitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModuleCentralizationIIoT.Domain.Entities.ModuleIIoT", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
