<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModuleCentralizationIIoT.Contracts\ModuleCentralizationIIoT.Contracts.csproj" />
    <ProjectReference Include="..\ModuleCentralizationIIoT.DataAccess\ModuleCentralizationIIoT.DataAccess.csproj" />
    <ProjectReference Include="..\ModuleCentralizationIIoT.Domain\ModuleCentralizationIIoT.Domain.csproj" />
    <ProjectReference Include="..\ModuleCentralizationIIoT.GrpcProtos\ModuleCentralizationIIoT.GrpcProtos\ModuleCentralizationIIoT.GrpcProtos.csproj" />
  </ItemGroup>

</Project>
